# Gopkg.toml example
#
# Refer to https://golang.github.io/dep/docs/Gopkg.toml.html
# for detailed Gopkg.toml documentation.
#
# required = ["github.com/user/thing/cmd/thing"]
# ignored = ["github.com/user/project/pkgX", "bitbucket.org/user/project/pkgA/pkgY"]
#
# [[constraint]]
#   name = "github.com/user/project"
#   version = "1.0.0"
#
# [[constraint]]
#   name = "github.com/user/project2"
#   branch = "dev"
#   source = "github.com/myfork/project2"
#
# [[override]]
#   name = "github.com/x/y"
#   version = "2.4.0"
#
# [prune]
#   non-go = false
#   go-tests = true
#   unused-packages = true


[[constraint]]
  name = "cloud.google.com/go"
  version = "0.33.1"

[[constraint]]
  name = "github.com/dgrijalva/jwt-go"
  version = "3.2.0"

[[constraint]]
  name = "github.com/gin-gonic/gin"
  version = "1.3.0"

[[constraint]]
  name = "github.com/go-redis/redis"
  version = "6.14.2"

[[constraint]]
  name = "github.com/gofrs/uuid"
  version = "3.1.2"

[[constraint]]
  name = "github.com/golang-migrate/migrate"
  version = "3.5.4"

[[constraint]]
  name = "github.com/gosimple/slug"
  version = "1.3.0"

[[constraint]]
  branch = "master"
  name = "github.com/hooklift/gowsdl"

[[constraint]]
  branch = "master"
  name = "github.com/icrowley/fake"

[[constraint]]
  name = "github.com/jinzhu/gorm"
  version = "1.9.1"

[[constraint]]
  name = "github.com/joho/godotenv"
  version = "1.3.0"

[[constraint]]
  name = "github.com/jung-kurt/gofpdf"
  version = "1.0.0"

[[constraint]]
  name = "github.com/kelseyhightower/envconfig"
  version = "1.3.0"

[[constraint]]
  name = "github.com/lib/pq"
  version = "1.0.0"

[[constraint]]
  name = "github.com/pkg/errors"
  version = "0.8.0"

[[constraint]]
  name = "github.com/sirupsen/logrus"
  version = "1.2.0"

[[constraint]]
  name = "github.com/spf13/cobra"
  version = "0.0.3"

[[constraint]]
  branch = "master"
  name = "google.golang.org/api"

[[constraint]]
  name = "gopkg.in/guregu/null.v3"
  version = "3.4.0"

[[constraint]]
  name = "gopkg.in/mailgun/mailgun-go.v1"
  version = "1.1.1"

[prune]
  go-tests = true
  unused-packages = true

[[constraint]]
  name = "go.mongodb.org/mongo-driver"
  version = "~1.1.1"

[[constraint]]
  name = "github.com/360EntSecGroup-Skylar/excelize"
  version = "2.0.1"
